spring.datasource.url=jdbc:postgresql://localhost:5432/miawpawdb

spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.data.jpa: trace
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driverClassName=org.postgresql.Driver

jwt.secret=68*aq4nif0-xm4a8=!qlk2flmy&ca-q9x&n*ii4kf6%ijcwe9%

cors.allowed-origins=http://localhost:8080

admin.username=admin

admin.password=admin

cloudinary.cloud-name=dmyyxyf4y
cloudinary.api-key=363553155252694
cloudinary.api-secret=TgEBxWy1pVNi4jwqMbsS7xhDlK4